// WARNING: Do not modify this file! This file is automatically generated by running 'scripts/generate_asset_references.py'.

using UnityEngine;
using UnityEditor;
using DungeonStrike.Source.Assets;

namespace DungeonStrike.Source.Assets.Editor
{
  public class AssetLinker : MonoBehaviour
  {
    public static void LinkAssets(AssetRefs refs)
    {
      refs.Soldier = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Prefabs/Units/Soldier.prefab");
      refs.SoldierWinter = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Soldier_ru_winter.mat");
      refs.SoldierBlack = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Soldier_ru_black.mat");
      refs.SoldierVestGreen = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Vest_green.mat");
      refs.SoldierGorka = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Soldier_ru_Gorka.mat");
      refs.SoldierVestBlack = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Vest_black.mat");
      refs.SoldierForest = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Soldier_ru_forest.mat");
      refs.Soldier02HelmetKhaki = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Materials/Soldier_02_helmet_khaki.mat");
      refs.SoldierBagsGreen = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Bags_green.mat");
      refs.SoldierJungle = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Soldier_ru_Jungle.mat");
      refs.SoldierHelmetBlack = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Helmet_black.mat");
      refs.SoldierBagsKhaki = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Bags_khaki.mat");
      refs.Soldier02BodyGorka = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Materials/Soldier_02_body_gorka.mat");
      refs.SoldierHelmetKhaki = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Helmet_khaki.mat");
      refs.SoldierHelmetGreen = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Helmet_green.mat");
      refs.SoldierDesert = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Soldier_ru_desert.mat");
      refs.SoldierVestKhaki = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Vest_khaki.mat");
      refs.SoldierBagsBlack = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Bags_black.mat");
      refs.Soldier02BagsKhaki = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Materials/Soldier_02_bags_khaki.mat");
      refs.SoldierSurpat = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Soldier_ru_surpat.mat");
      refs.Soldier02VestKhaki = AssetDatabase.LoadAssetAtPath<Material>("Assets/ThirdParty/Soldier_ru/Materials/Soldier_02_vest_khaki.mat");
    }
  }
}
