(ns dungeonstrike.test-message-values
  "Stores useful test values for message fields."
  (:require [dungeonstrike.dev :as dev]))
(dev/require-dev-helpers)

(def positions
  {:0&0+7
   [{:m/x -7 :m/y -7}
    {:m/x -6 :m/y -7}
    {:m/x -5 :m/y -7}
    {:m/x -4 :m/y -7}
    {:m/x -3 :m/y -7}
    {:m/x -2 :m/y -7}
    {:m/x -1 :m/y -7}
    {:m/x 0 :m/y -7}
    {:m/x 1 :m/y -7}
    {:m/x 2 :m/y -7}
    {:m/x 3 :m/y -7}
    {:m/x 4 :m/y -7}
    {:m/x 5 :m/y -7}
    {:m/x 6 :m/y -7}
    {:m/x 7 :m/y -7}
    {:m/x -7 :m/y -6}
    {:m/x -6 :m/y -6}
    {:m/x -5 :m/y -6}
    {:m/x -4 :m/y -6}
    {:m/x -3 :m/y -6}
    {:m/x -2 :m/y -6}
    {:m/x -1 :m/y -6}
    {:m/x 0 :m/y -6}
    {:m/x 1 :m/y -6}
    {:m/x 2 :m/y -6}
    {:m/x 3 :m/y -6}
    {:m/x 4 :m/y -6}
    {:m/x 5 :m/y -6}
    {:m/x 6 :m/y -6}
    {:m/x 7 :m/y -6}
    {:m/x -7 :m/y -5}
    {:m/x -6 :m/y -5}
    {:m/x -5 :m/y -5}
    {:m/x -4 :m/y -5}
    {:m/x -3 :m/y -5}
    {:m/x -2 :m/y -5}
    {:m/x -1 :m/y -5}
    {:m/x 0 :m/y -5}
    {:m/x 1 :m/y -5}
    {:m/x 2 :m/y -5}
    {:m/x 3 :m/y -5}
    {:m/x 4 :m/y -5}
    {:m/x 5 :m/y -5}
    {:m/x 6 :m/y -5}
    {:m/x 7 :m/y -5}
    {:m/x -7 :m/y -4}
    {:m/x -6 :m/y -4}
    {:m/x -5 :m/y -4}
    {:m/x -4 :m/y -4}
    {:m/x -3 :m/y -4}
    {:m/x -2 :m/y -4}
    {:m/x -1 :m/y -4}
    {:m/x 0 :m/y -4}
    {:m/x 1 :m/y -4}
    {:m/x 2 :m/y -4}
    {:m/x 3 :m/y -4}
    {:m/x 4 :m/y -4}
    {:m/x 5 :m/y -4}
    {:m/x 6 :m/y -4}
    {:m/x 7 :m/y -4}
    {:m/x -7 :m/y -3}
    {:m/x -6 :m/y -3}
    {:m/x -5 :m/y -3}
    {:m/x -4 :m/y -3}
    {:m/x -3 :m/y -3}
    {:m/x -2 :m/y -3}
    {:m/x -1 :m/y -3}
    {:m/x 0 :m/y -3}
    {:m/x 1 :m/y -3}
    {:m/x 2 :m/y -3}
    {:m/x 3 :m/y -3}
    {:m/x 4 :m/y -3}
    {:m/x 5 :m/y -3}
    {:m/x 6 :m/y -3}
    {:m/x 7 :m/y -3}
    {:m/x -7 :m/y -2}
    {:m/x -6 :m/y -2}
    {:m/x -5 :m/y -2}
    {:m/x -4 :m/y -2}
    {:m/x -3 :m/y -2}
    {:m/x -2 :m/y -2}
    {:m/x -1 :m/y -2}
    {:m/x 0 :m/y -2}
    {:m/x 1 :m/y -2}
    {:m/x 2 :m/y -2}
    {:m/x 3 :m/y -2}
    {:m/x 4 :m/y -2}
    {:m/x 5 :m/y -2}
    {:m/x 6 :m/y -2}
    {:m/x 7 :m/y -2}
    {:m/x -7 :m/y -1}
    {:m/x -6 :m/y -1}
    {:m/x -5 :m/y -1}
    {:m/x -4 :m/y -1}
    {:m/x -3 :m/y -1}
    {:m/x -2 :m/y -1}
    {:m/x -1 :m/y -1}
    {:m/x 0 :m/y -1}
    {:m/x 1 :m/y -1}
    {:m/x 2 :m/y -1}
    {:m/x 3 :m/y -1}
    {:m/x 4 :m/y -1}
    {:m/x 5 :m/y -1}
    {:m/x 6 :m/y -1}
    {:m/x 7 :m/y -1}
    {:m/x -7 :m/y 0}
    {:m/x -6 :m/y 0}
    {:m/x -5 :m/y 0}
    {:m/x -4 :m/y 0}
    {:m/x -3 :m/y 0}
    {:m/x -2 :m/y 0}
    {:m/x -1 :m/y 0}
    {:m/x 1 :m/y 0}
    {:m/x 2 :m/y 0}
    {:m/x 3 :m/y 0}
    {:m/x 4 :m/y 0}
    {:m/x 5 :m/y 0}
    {:m/x 6 :m/y 0}
    {:m/x 7 :m/y 0}
    {:m/x -7 :m/y 7}
    {:m/x -6 :m/y 7}
    {:m/x -5 :m/y 7}
    {:m/x -4 :m/y 7}
    {:m/x -3 :m/y 7}
    {:m/x -2 :m/y 7}
    {:m/x -1 :m/y 7}
    {:m/x 0 :m/y 7}
    {:m/x 1 :m/y 7}
    {:m/x 2 :m/y 7}
    {:m/x 3 :m/y 7}
    {:m/x 4 :m/y 7}
    {:m/x 5 :m/y 7}
    {:m/x 6 :m/y 7}
    {:m/x 7 :m/y 7}
    {:m/x -7 :m/y 6}
    {:m/x -6 :m/y 6}
    {:m/x -5 :m/y 6}
    {:m/x -4 :m/y 6}
    {:m/x -3 :m/y 6}
    {:m/x -2 :m/y 6}
    {:m/x -1 :m/y 6}
    {:m/x 0 :m/y 6}
    {:m/x 1 :m/y 6}
    {:m/x 2 :m/y 6}
    {:m/x 3 :m/y 6}
    {:m/x 4 :m/y 6}
    {:m/x 5 :m/y 6}
    {:m/x 6 :m/y 6}
    {:m/x 7 :m/y 6}
    {:m/x -7 :m/y 5}
    {:m/x -6 :m/y 5}
    {:m/x -5 :m/y 5}
    {:m/x -4 :m/y 5}
    {:m/x -3 :m/y 5}
    {:m/x -2 :m/y 5}
    {:m/x -1 :m/y 5}
    {:m/x 0 :m/y 5}
    {:m/x 1 :m/y 5}
    {:m/x 2 :m/y 5}
    {:m/x 3 :m/y 5}
    {:m/x 4 :m/y 5}
    {:m/x 5 :m/y 5}
    {:m/x 6 :m/y 5}
    {:m/x 7 :m/y 5}
    {:m/x -7 :m/y 4}
    {:m/x -6 :m/y 4}
    {:m/x -5 :m/y 4}
    {:m/x -4 :m/y 4}
    {:m/x -3 :m/y 4}
    {:m/x -2 :m/y 4}
    {:m/x -1 :m/y 4}
    {:m/x 0 :m/y 4}
    {:m/x 1 :m/y 4}
    {:m/x 2 :m/y 4}
    {:m/x 3 :m/y 4}
    {:m/x 4 :m/y 4}
    {:m/x 5 :m/y 4}
    {:m/x 6 :m/y 4}
    {:m/x 7 :m/y 4}
    {:m/x -7 :m/y 3}
    {:m/x -6 :m/y 3}
    {:m/x -5 :m/y 3}
    {:m/x -4 :m/y 3}
    {:m/x -3 :m/y 3}
    {:m/x -2 :m/y 3}
    {:m/x -1 :m/y 3}
    {:m/x 0 :m/y 3}
    {:m/x 1 :m/y 3}
    {:m/x 2 :m/y 3}
    {:m/x 3 :m/y 3}
    {:m/x 4 :m/y 3}
    {:m/x 5 :m/y 3}
    {:m/x 6 :m/y 3}
    {:m/x 7 :m/y 3}
    {:m/x -7 :m/y 2}
    {:m/x -6 :m/y 2}
    {:m/x -5 :m/y 2}
    {:m/x -4 :m/y 2}
    {:m/x -3 :m/y 2}
    {:m/x -2 :m/y 2}
    {:m/x -1 :m/y 2}
    {:m/x 0 :m/y 2}
    {:m/x 1 :m/y 2}
    {:m/x 2 :m/y 2}
    {:m/x 3 :m/y 2}
    {:m/x 4 :m/y 2}
    {:m/x 5 :m/y 2}
    {:m/x 6 :m/y 2}
    {:m/x 7 :m/y 2}
    {:m/x -7 :m/y 1}
    {:m/x -6 :m/y 1}
    {:m/x -5 :m/y 1}
    {:m/x -4 :m/y 1}
    {:m/x -3 :m/y 1}
    {:m/x -2 :m/y 1}
    {:m/x -1 :m/y 1}
    {:m/x 0 :m/y 1}
    {:m/x 1 :m/y 1}
    {:m/x 2 :m/y 1}
    {:m/x 3 :m/y 1}
    {:m/x 4 :m/y 1}
    {:m/x 5 :m/y 1}
    {:m/x 6 :m/y 1}
    {:m/x 7 :m/y 1}]})
