// WARNING: Do not modify this file! This file is automatically
// generated by running 'scripts/generate_asset_references.py'.

using UnityEngine;
using DungeonStrike.Source.Messaging;

namespace DungeonStrike.Source.Assets
{
  public class AssetUtil
  {
    public static GameObject InstantiatePrefab(AssetRefs refs, PrefabName name, Vector3 position)
    {
      switch (name)
      {
        case PrefabName.Soldier:
          return Object.Instantiate(refs.Soldier, position, Quaternion.identity);
      }
      throw new System.InvalidOperationException("Unknown asset name: " + name);
    }
    
    public static Material GetMaterial(AssetRefs refs, MaterialName name)
    {
      switch (name)
      {
        case MaterialName.SoldierWinter:
          return refs.SoldierWinter;
        case MaterialName.SoldierBlack:
          return refs.SoldierBlack;
        case MaterialName.SoldierVestGreen:
          return refs.SoldierVestGreen;
        case MaterialName.SoldierGorka:
          return refs.SoldierGorka;
        case MaterialName.SoldierVestBlack:
          return refs.SoldierVestBlack;
        case MaterialName.SoldierForest:
          return refs.SoldierForest;
        case MaterialName.Soldier02HelmetKhaki:
          return refs.Soldier02HelmetKhaki;
        case MaterialName.SoldierBagsGreen:
          return refs.SoldierBagsGreen;
        case MaterialName.SoldierJungle:
          return refs.SoldierJungle;
        case MaterialName.SoldierHelmetBlack:
          return refs.SoldierHelmetBlack;
        case MaterialName.SoldierBagsKhaki:
          return refs.SoldierBagsKhaki;
        case MaterialName.Soldier02BodyGorka:
          return refs.Soldier02BodyGorka;
        case MaterialName.SoldierHelmetKhaki:
          return refs.SoldierHelmetKhaki;
        case MaterialName.SoldierHelmetGreen:
          return refs.SoldierHelmetGreen;
        case MaterialName.SoldierDesert:
          return refs.SoldierDesert;
        case MaterialName.SoldierVestKhaki:
          return refs.SoldierVestKhaki;
        case MaterialName.SoldierBagsBlack:
          return refs.SoldierBagsBlack;
        case MaterialName.Soldier02BagsKhaki:
          return refs.Soldier02BagsKhaki;
        case MaterialName.SoldierSurpat:
          return refs.SoldierSurpat;
        case MaterialName.Soldier02VestKhaki:
          return refs.Soldier02VestKhaki;
      }
      throw new System.InvalidOperationException("Unknown asset name: " + name);
    }
    
  }
}
