// WARNING: Do not modify this file! This file is automatically
// generated by running 'scripts/generate_asset_references.py'.

using UnityEngine;
using DungeonStrike.Source.Messaging;

namespace DungeonStrike.Source.Assets
{
  public class AssetUtil
  {
    public static GameObject InstantiatePrefab(AssetRefs refs, PrefabName name, Vector3 position)
    {
      switch (name)
      {
        case PrefabName.Soldier:
          return Object.Instantiate(refs.Soldier, position, Quaternion.identity);
      }
      throw new System.InvalidOperationException("Unknown asset name: " + name);
    }
    
    public static Material GetMaterial(AssetRefs refs, MaterialName name)
    {
      switch (name)
      {
        case MaterialName.SoldierWinter:
          return refs.SoldierWinter;
        case MaterialName.SoldierBlack:
          return refs.SoldierBlack;
        case MaterialName.SoldierVestGreen:
          return refs.SoldierVestGreen;
        case MaterialName.SoldierGorka:
          return refs.SoldierGorka;
        case MaterialName.SoldierVestBlack:
          return refs.SoldierVestBlack;
        case MaterialName.SoldierForest:
          return refs.SoldierForest;
        case MaterialName.Soldier02HelmetKhaki:
          return refs.Soldier02HelmetKhaki;
        case MaterialName.SoldierBagsGreen:
          return refs.SoldierBagsGreen;
        case MaterialName.SoldierJungle:
          return refs.SoldierJungle;
        case MaterialName.SoldierHelmetBlack:
          return refs.SoldierHelmetBlack;
        case MaterialName.SoldierBagsKhaki:
          return refs.SoldierBagsKhaki;
        case MaterialName.Soldier02BodyGorka:
          return refs.Soldier02BodyGorka;
        case MaterialName.SoldierHelmetKhaki:
          return refs.SoldierHelmetKhaki;
        case MaterialName.SoldierHelmetGreen:
          return refs.SoldierHelmetGreen;
        case MaterialName.SoldierDesert:
          return refs.SoldierDesert;
        case MaterialName.SoldierVestKhaki:
          return refs.SoldierVestKhaki;
        case MaterialName.SoldierBagsBlack:
          return refs.SoldierBagsBlack;
        case MaterialName.Soldier02BagsKhaki:
          return refs.Soldier02BagsKhaki;
        case MaterialName.SoldierSurpat:
          return refs.SoldierSurpat;
        case MaterialName.Soldier02VestKhaki:
          return refs.Soldier02VestKhaki;
      }
      throw new System.InvalidOperationException("Unknown asset name: " + name);
    }
    
    public static Sprite GetSprite(AssetRefs refs, SpriteName name)
    {
      switch (name)
      {
        case SpriteName.ShadowCardPowerSymbolShadowBig:
          return refs.ShadowCardPowerSymbolShadowBig;
        case SpriteName.WaterCardEcWaterBackBig:
          return refs.WaterCardEcWaterBackBig;
        case SpriteName.EarthCardPowerBigEarth:
          return refs.EarthCardPowerBigEarth;
        case SpriteName.WaterCardRarityRank2:
          return refs.WaterCardRarityRank2;
        case SpriteName.AirCardRarityRank1Big:
          return refs.AirCardRarityRank1Big;
        case SpriteName.FireCardRarityRank1Big:
          return refs.FireCardRarityRank1Big;
        case SpriteName.LightCardCostSymbolBigLight:
          return refs.LightCardCostSymbolBigLight;
        case SpriteName.LightCardHealthSymbolBigLightShadowed:
          return refs.LightCardHealthSymbolBigLightShadowed;
        case SpriteName.LightCardCostSymbolBigLightShadowed:
          return refs.LightCardCostSymbolBigLightShadowed;
        case SpriteName.LightCardPowerSymbolBigLightShadowed:
          return refs.LightCardPowerSymbolBigLightShadowed;
        case SpriteName.FireCardScorchedEarthArtBig:
          return refs.FireCardScorchedEarthArtBig;
        case SpriteName.FireCardCostSymbol:
          return refs.FireCardCostSymbol;
        case SpriteName.AirCardElAirHeadingSeparate:
          return refs.AirCardElAirHeadingSeparate;
        case SpriteName.AirCardElementalAirCardBack:
          return refs.AirCardElementalAirCardBack;
        case SpriteName.LightCardRarityRank2Big:
          return refs.LightCardRarityRank2Big;
        case SpriteName.FireCardPowerSymbolFireShadowed:
          return refs.FireCardPowerSymbolFireShadowed;
        case SpriteName.WaterCardRarityRank4:
          return refs.WaterCardRarityRank4;
        case SpriteName.EarthCardRarityRank5:
          return refs.EarthCardRarityRank5;
        case SpriteName.FireCardRarityRank3Big:
          return refs.FireCardRarityRank3Big;
        case SpriteName.LightCardLightCardBigFrontShadowed:
          return refs.LightCardLightCardBigFrontShadowed;
        case SpriteName.FireCardRarityRank5Big:
          return refs.FireCardRarityRank5Big;
        case SpriteName.EarthCardEcEarthFrontBig:
          return refs.EarthCardEcEarthFrontBig;
        case SpriteName.EarthCardEcEarthFrontNoHeading:
          return refs.EarthCardEcEarthFrontNoHeading;
        case SpriteName.EarthCardRarityRank4:
          return refs.EarthCardRarityRank4;
        case SpriteName.WaterCardEcWaterFrontBigShadowed:
          return refs.WaterCardEcWaterFrontBigShadowed;
        case SpriteName.AirCardHealthSymbolAir:
          return refs.AirCardHealthSymbolAir;
        case SpriteName.LightCardLightCardBody:
          return refs.LightCardLightCardBody;
        case SpriteName.AirCardElementalAirCardArtFrame:
          return refs.AirCardElementalAirCardArtFrame;
        case SpriteName.ShadowCardRarityRank1Big:
          return refs.ShadowCardRarityRank1Big;
        case SpriteName.WaterCardWaterArtworkBig:
          return refs.WaterCardWaterArtworkBig;
        case SpriteName.AirCardElementalAirCardBackShadowed:
          return refs.AirCardElementalAirCardBackShadowed;
        case SpriteName.ShadowCardHealthSymbolShadowBig:
          return refs.ShadowCardHealthSymbolShadowBig;
        case SpriteName.FireCardPowerSymbol:
          return refs.FireCardPowerSymbol;
        case SpriteName.ShadowCardShadowFontBigOutlined:
          return refs.ShadowCardShadowFontBigOutlined;
        case SpriteName.FireCardElFiHeadingSeparate:
          return refs.FireCardElFiHeadingSeparate;
        case SpriteName.ShadowCardCostSymbolShadowBigOutlined:
          return refs.ShadowCardCostSymbolShadowBigOutlined;
        case SpriteName.AirCardRarityRank2Big:
          return refs.AirCardRarityRank2Big;
        case SpriteName.WaterCardEcWaterFrontHeading:
          return refs.WaterCardEcWaterFrontHeading;
        case SpriteName.LightCardRarityRank3Big:
          return refs.LightCardRarityRank3Big;
        case SpriteName.ShadowCardPowerSymbolShadowBigOutlined:
          return refs.ShadowCardPowerSymbolShadowBigOutlined;
        case SpriteName.AirCardRarityRank5Big:
          return refs.AirCardRarityRank5Big;
        case SpriteName.EarthCardRarityRank1:
          return refs.EarthCardRarityRank1;
        case SpriteName.AirCardCostSymbolAirBig:
          return refs.AirCardCostSymbolAirBig;
        case SpriteName.WaterCardCostBigSymbol:
          return refs.WaterCardCostBigSymbol;
        case SpriteName.ShadowCardShadowBigArtMask:
          return refs.ShadowCardShadowBigArtMask;
        case SpriteName.AirCardElementalAirCardFrontShadowed:
          return refs.AirCardElementalAirCardFrontShadowed;
        case SpriteName.LightCardLightArtBig:
          return refs.LightCardLightArtBig;
        case SpriteName.ShadowCardShadowHeadingSeparated:
          return refs.ShadowCardShadowHeadingSeparated;
        case SpriteName.EarthCardEcEarthArtFrameBig:
          return refs.EarthCardEcEarthArtFrameBig;
        case SpriteName.AirCardElementalAirCardArtMask:
          return refs.AirCardElementalAirCardArtMask;
        case SpriteName.WaterCardRarityRank3:
          return refs.WaterCardRarityRank3;
        case SpriteName.LightCardHealthSymbolBigLight:
          return refs.LightCardHealthSymbolBigLight;
        case SpriteName.ShadowCardShadowFrontBig:
          return refs.ShadowCardShadowFrontBig;
        case SpriteName.EarthCardHealthBigEarthShadowed:
          return refs.EarthCardHealthBigEarthShadowed;
        case SpriteName.WaterCardPowerBigSymbol:
          return refs.WaterCardPowerBigSymbol;
        case SpriteName.AirCardPowerSymbolAirBigShadowed:
          return refs.AirCardPowerSymbolAirBigShadowed;
        case SpriteName.AirCardHealthSymbolAirBigShadowed:
          return refs.AirCardHealthSymbolAirBigShadowed;
        case SpriteName.WaterCardEcWaterFrontBig:
          return refs.WaterCardEcWaterFrontBig;
        case SpriteName.AirCardElementalAirCardFront:
          return refs.AirCardElementalAirCardFront;
        case SpriteName.ShadowCardShadowBodyFront:
          return refs.ShadowCardShadowBodyFront;
        case SpriteName.AirCardRarityRank3Big:
          return refs.AirCardRarityRank3Big;
        case SpriteName.ShadowCardShadowArtFrameBig:
          return refs.ShadowCardShadowArtFrameBig;
        case SpriteName.LightCardRarityRank5Big:
          return refs.LightCardRarityRank5Big;
        case SpriteName.LightCardLightCardBigBackShadowed:
          return refs.LightCardLightCardBigBackShadowed;
        case SpriteName.FireCardElementalFireCardFrontShadowed:
          return refs.FireCardElementalFireCardFrontShadowed;
        case SpriteName.WaterCardHealthBigSymbol:
          return refs.WaterCardHealthBigSymbol;
        case SpriteName.ShadowCardRarityRank4Big:
          return refs.ShadowCardRarityRank4Big;
        case SpriteName.ShadowCardRarityRank3Big:
          return refs.ShadowCardRarityRank3Big;
        case SpriteName.ShadowCardShadowArtBig:
          return refs.ShadowCardShadowArtBig;
        case SpriteName.FireCardElementalFireCardBack:
          return refs.FireCardElementalFireCardBack;
        case SpriteName.EarthCardCostBigEarth:
          return refs.EarthCardCostBigEarth;
        case SpriteName.LightCardLightCardBigFront:
          return refs.LightCardLightCardBigFront;
        case SpriteName.LightCardPowerSymbolBigLight:
          return refs.LightCardPowerSymbolBigLight;
        case SpriteName.WaterCardEcWaterFrontNoHeading:
          return refs.WaterCardEcWaterFrontNoHeading;
        case SpriteName.FireCardHealthSymbolFireShadowed:
          return refs.FireCardHealthSymbolFireShadowed;
        case SpriteName.ShadowCardShadowBackBigOutlined:
          return refs.ShadowCardShadowBackBigOutlined;
        case SpriteName.EarthCardRarityRank2:
          return refs.EarthCardRarityRank2;
        case SpriteName.LightCardLightCardHeading:
          return refs.LightCardLightCardHeading;
        case SpriteName.FireCardElFiCardBodyFront:
          return refs.FireCardElFiCardBodyFront;
        case SpriteName.EarthCardRarityRank3:
          return refs.EarthCardRarityRank3;
        case SpriteName.EarthCardEcEarthMaskBig:
          return refs.EarthCardEcEarthMaskBig;
        case SpriteName.ShadowCardHealthSymbolShadowBigOutlined:
          return refs.ShadowCardHealthSymbolShadowBigOutlined;
        case SpriteName.WaterCardEcWaterArtFrameBig:
          return refs.WaterCardEcWaterArtFrameBig;
        case SpriteName.ShadowCardRarityRank5Big:
          return refs.ShadowCardRarityRank5Big;
        case SpriteName.ShadowCardRarityRank2Big:
          return refs.ShadowCardRarityRank2Big;
        case SpriteName.ShadowCardShadowBackBig:
          return refs.ShadowCardShadowBackBig;
        case SpriteName.LightCardArtMaskBigLight:
          return refs.LightCardArtMaskBigLight;
        case SpriteName.EarthCardPowerBigEarthShadowed:
          return refs.EarthCardPowerBigEarthShadowed;
        case SpriteName.EarthCardEcEarthBackBig:
          return refs.EarthCardEcEarthBackBig;
        case SpriteName.EarthCardEcEarthFrontHeading:
          return refs.EarthCardEcEarthFrontHeading;
        case SpriteName.FireCardCostSymbolFireShadowed:
          return refs.FireCardCostSymbolFireShadowed;
        case SpriteName.LightCardPortraitFrameBigLight:
          return refs.LightCardPortraitFrameBigLight;
        case SpriteName.WaterCardRarityRank1:
          return refs.WaterCardRarityRank1;
        case SpriteName.WaterCardEcWaterMaskBig:
          return refs.WaterCardEcWaterMaskBig;
        case SpriteName.ShadowCardCostSymbolShadowBig:
          return refs.ShadowCardCostSymbolShadowBig;
        case SpriteName.FireCardElementalFireCardFront:
          return refs.FireCardElementalFireCardFront;
        case SpriteName.AirCardElAirCardBodyFront:
          return refs.AirCardElAirCardBodyFront;
        case SpriteName.EarthCardEcEarthFrontBigShadowed:
          return refs.EarthCardEcEarthFrontBigShadowed;
        case SpriteName.AirCardArtworkAirBig:
          return refs.AirCardArtworkAirBig;
        case SpriteName.EarthCardEcEarthBackBigShadowed:
          return refs.EarthCardEcEarthBackBigShadowed;
        case SpriteName.FireCardRarityRank4Big:
          return refs.FireCardRarityRank4Big;
        case SpriteName.AirCardPowerSymbolAir:
          return refs.AirCardPowerSymbolAir;
        case SpriteName.FireCardElementalFireCardArtMask:
          return refs.FireCardElementalFireCardArtMask;
        case SpriteName.WaterCardEcWaterBackBigShadowed:
          return refs.WaterCardEcWaterBackBigShadowed;
        case SpriteName.AirCardRarityRank4Big:
          return refs.AirCardRarityRank4Big;
        case SpriteName.FireCardRarityRank2Big:
          return refs.FireCardRarityRank2Big;
        case SpriteName.EarthCardHealthBigEarth:
          return refs.EarthCardHealthBigEarth;
        case SpriteName.LightCardRarityRank1Big:
          return refs.LightCardRarityRank1Big;
        case SpriteName.FireCardElementalFireCardBackShadowed:
          return refs.FireCardElementalFireCardBackShadowed;
        case SpriteName.LightCardRarityRank4Big:
          return refs.LightCardRarityRank4Big;
        case SpriteName.AirCardCostSymbolAirBigShadowed:
          return refs.AirCardCostSymbolAirBigShadowed;
        case SpriteName.FireCardElementalFireCardArtFrame:
          return refs.FireCardElementalFireCardArtFrame;
        case SpriteName.EarthCardEarthArtworkBig:
          return refs.EarthCardEarthArtworkBig;
        case SpriteName.FireCardHealthSymbol:
          return refs.FireCardHealthSymbol;
        case SpriteName.WaterCardRarityRank5:
          return refs.WaterCardRarityRank5;
        case SpriteName.EarthCardCostBigEarthShadowed:
          return refs.EarthCardCostBigEarthShadowed;
        case SpriteName.LightCardLightCardBigBack:
          return refs.LightCardLightCardBigBack;
      }
      throw new System.InvalidOperationException("Unknown asset name: " + name);
    }
    
  }
}
