// WARNING: Do not modify this file! This file is automatically generated by running 'scripts/generate_asset_references.py'.

using UnityEngine;

namespace DungeonStrike.Source.Assets
{
  public class AssetRefs : MonoBehaviour
  {
    public GameObject Soldier;
    public Material SoldierWinter;
    public Material SoldierBlack;
    public Material SoldierVestGreen;
    public Material SoldierGorka;
    public Material SoldierVestBlack;
    public Material SoldierForest;
    public Material Soldier02HelmetKhaki;
    public Material SoldierBagsGreen;
    public Material SoldierJungle;
    public Material SoldierHelmetBlack;
    public Material SoldierBagsKhaki;
    public Material Soldier02BodyGorka;
    public Material SoldierHelmetKhaki;
    public Material SoldierHelmetGreen;
    public Material SoldierDesert;
    public Material SoldierVestKhaki;
    public Material SoldierBagsBlack;
    public Material Soldier02BagsKhaki;
    public Material SoldierSurpat;
    public Material Soldier02VestKhaki;
  }
}
