// WARNING: Do not modify this file! This file is automatically
// generated by running 'scripts/generate_asset_references.py'.

using UnityEngine;

namespace DungeonStrike.Source.Assets
{
  public class AssetUtil
  {
    public static GameObject InstantiateGameObject(AssetRefs refs, string name, Vector3 position)
    {
      switch (name)
      {
        case "Soldier":
          return Object.Instantiate(refs.Soldier, position, Quaternion.identity);
      }
      throw new System.InvalidOperationException("Unknown asset name: " + name);
    }
    
    public static Material GetMaterial(AssetRefs refs, string name)
    {
      switch (name)
      {
        case "SoldierWinter":
          return refs.SoldierWinter;
        case "SoldierBlack":
          return refs.SoldierBlack;
        case "SoldierVestGreen":
          return refs.SoldierVestGreen;
        case "SoldierGorka":
          return refs.SoldierGorka;
        case "SoldierVestBlack":
          return refs.SoldierVestBlack;
        case "SoldierForest":
          return refs.SoldierForest;
        case "Soldier02HelmetKhaki":
          return refs.Soldier02HelmetKhaki;
        case "SoldierBagsGreen":
          return refs.SoldierBagsGreen;
        case "SoldierJungle":
          return refs.SoldierJungle;
        case "SoldierHelmetBlack":
          return refs.SoldierHelmetBlack;
        case "SoldierBagsKhaki":
          return refs.SoldierBagsKhaki;
        case "Soldier02BodyGorka":
          return refs.Soldier02BodyGorka;
        case "SoldierHelmetKhaki":
          return refs.SoldierHelmetKhaki;
        case "SoldierHelmetGreen":
          return refs.SoldierHelmetGreen;
        case "SoldierDesert":
          return refs.SoldierDesert;
        case "SoldierVestKhaki":
          return refs.SoldierVestKhaki;
        case "SoldierBagsBlack":
          return refs.SoldierBagsBlack;
        case "Soldier02BagsKhaki":
          return refs.Soldier02BagsKhaki;
        case "SoldierSurpat":
          return refs.SoldierSurpat;
        case "Soldier02VestKhaki":
          return refs.Soldier02VestKhaki;
      }
      throw new System.InvalidOperationException("Unknown asset name: " + name);
    }
    
  }
}
